# These are supported funding model platforms

github: [ahmadawais]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://pay.paddle.com/checkout/540217', 'https://pay.paddle.com/checkout/527254', 'https://pay.paddle.com/checkout/515568', 'https://pay.paddle.com/checkout/527253']
